# Generated by Django 5.0.6 on 2024-06-21 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ninjas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('set', 'Set'), ('swap', 'Swap')], max_length=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('ongoing', 'Ongoing'), ('unsuccessful', 'Unsuccessful'), ('future', 'Future')], max_length=14)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ninja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ninjas.ninja')),
            ],
        ),
    ]
